### ISSUE TITLE
How to display month in a text

### ISSUE THREAD

**Issue by AnuragVadd** [adamstyrc/parking-app#4]
Hey Adam! really loving this plugin. I just have a quick question: in your parking space project, how did you display the month with the year?

**Comment by adamstyrc** [comment]
@AnuragVadd 
If you mean Planner view then it's not a part of [Calendarro](https://github.com/adamstyrc/calendarro) but I print it myself with just a Text widget on top of Calendarro widget ;)

**Comment by AnuragVadd** [comment]
Could you please share that line of code (to display the month), I tried to run your app in my IDE and find out the line using inspector but it seems some of the plugins were outdated and so the app wouldn't run.

**Comment by adamstyrc** [comment]
@AnuragVadd 
Here you go :)
https://github.com/adamstyrc/parking-app/blob/ce7faaf19e3dea15ba53a717d9af44573b0d0bdf/lib/ui/page/PlannerPage.dart#L81

**Comment by AnuragVadd** [comment]
Works perfectly fine, thank you SO much :)
